name: Bug form
description: Something went wrong.
body:
- type: textarea
  attributes:
    label: What happened?
    description: A concise description of what went wrong.
  validations:
    required: true
- type: textarea
  attributes:
    label: What was expected?
    description: A concise description of what was expected to happen.
- type: textarea
  attributes:
    label: Steps to reproduce
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See '...'
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: |
      Logs, links, screenshots, videos, or anything that may help us to resolve the issue.
    placeholder: |
      - /var/log/installer/ubuntu_desktop_installer.log
      - /var/log/installer/subiquity-server-debug.log
  validations:
    required: false
- type: markdown
  attributes:
    value: "Tip: You can drag and drop to attach files."
